apiVersion: v1
kind: Service
metadata:
  name: jieba-segmentor-service
spec:
  selector:
    ray.io/cluster: jieba-segmentor-cluster
    ray.io/node-type: head
  ports:
  - name: serve
    port: 8000
    targetPort: 8000
  type: ClusterIP

